CREATE DATABASE COMPANY;
USE COMPANY;


 CREATE TABLE DEPT_LOCATIONS(
     DNUMBER INTEGER NOT NULL,
     DLOCATION VARCHAR(20) NOT NULL,
	 PRIMARY KEY(DNUMBER,DLOCATION)
    );

	
 CREATE TABLE DEPENDENT(
     ESSN INTEGER NOT NULL,
     DEPENDENT_NAME VARCHAR(20) NOT NULL,
     SEX CHAR(1) NOT NULL,
     BDATE DATE NOT NULL,
     RELATIONSHIP VARCHAR(20) NOT NULL,
     PRIMARY KEY(ESSN,DEPENDENT_NAME)
     );
	
 CREATE TABLE PROJECT(
      PNAME VARCHAR(30) NOT NULL,
      PNUMBER INTEGER NOT NULL,
      PLOCATION VARCHAR(20) NOT NULL,
     DNUM INTEGER NOT NULL,
     PRIMARY KEY(PNUMBER)
     );
	
CREATE TABLE WORKS_ON(
     ESSN INTEGER NOT NULL,
     PNO INTEGER NOT NULL,
     HOURS DECIMAL(3,1),
     PRIMARY KEY(ESSN,PNO)
     );

CREATE TABLE DEPARTMENT(
     DNAME VARCHAR(20) NOT NULL,
     DNUMBER INTEGER NOT NULL,
     MGRSSN INTEGER NOT NULL,
     MGRSTARTDATE DATE NOT NULL,
     PRIMARY KEY(DNUMBER)
     );

CREATE TABLE EMPLOYEE (
      FNAME VARCHAR(20) NOT NULL,
      MINIT CHAR(1) NOT NULL,
	  LNAME VARCHAR(20) NOT NULL,
	  SSN INTEGER NOT NULL,
      BDATE DATE NOT NULL,
     ADDEESS VARCHAR(50) NOT NULL,
     SEX CHAR(1) NOT NULL,
     SALARY INTEGER NOT NULL,
     SUPERSSN INTEGER,
     DNO INTEGER NOT NULL,
     PRIMARY KEY(SSN)
     );
     
SET GLOBAL local_infile = true;

LOAD DATA LOCAL INFILE 'E:\\Education\\Semester 6\\Advanced database-CO527\\db.txt' INTO TABLE  DEPT_LOCATIONS FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'E:\\Education\\Semester 6\\Advanced database-CO527\\project.txt' INTO TABLE PROJECT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'E:\\Education\\Semester 6\\Advanced database-CO527\\works_on.txt' INTO TABLE WORKS_ON FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'E:\\Education\\Semester 6\\Advanced database-CO527\\EMPLOYEE.txt' INTO TABLE EMPLOYEE FIELDS TERMINATED BY '/' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'E:\\Education\\Semester 6\\Advanced database-CO527\\dependent.txt' INTO TABLE DEPENDENT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'E:\\Education\\Semester 6\\Advanced database-CO527\\department.txt' INTO TABLE DEPARTMENT FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';


ALTER TABLE WORKS_ON ADD FOREIGN KEY(PNO) REFERENCES PROJECT(PNUMBER) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE WORKS_ON ADD FOREIGN KEY(ESSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DEPENDENT ADD FOREIGN KEY(ESSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PROJECT ADD FOREIGN KEY(DNUM) REFERENCES DEPARTMENT(DNUMBER) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DEPT_LOCATIONS ADD FOREIGN KEY(DNUMBER) REFERENCES DEPARTMENT(DNUMBER) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE EMPLOYEE ADD FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNUMBER) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DEPARTMENT ADD FOREIGN KEY(MGRSSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE ON UPDATE CASCADE;

